#!/usr/bin/lua

--[[


Copyright (C) 2009-2011 startx <startx@plentyfact.org>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 3
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
http://www.gnu.org/copyleft/gpl.html

version 0.4.6.3

--]]

local status,err = pcall(
  function()
    dofile '/etc/interkomm/bootstrap.lua'
  end )
  if not status then
    os.exit()
  end

require 'ikm'

-- we start the actual daemons

local pid = posix.fork() 

if ( pid == -1 ) then
          print ("fork failed.")
elseif ( pid == 0 ) then
          ikm.spool.run(1)

else
          -- startin a second process for level 2 jobs
             ikm.spool.run(2)


end


